### ISSUE TITLE
TextField 在 size/typography 改變時會使 clear icon 跑位

### ISSUE THREAD

**Issue by BenChen21** [Mezzanine-UI/mezzanine#138]
### Describe the bug
TextField 在 size/typography 改變時會使 clear icon 跑位
Autocomplete, Select 等等使用到 TextField 的元件共同有這個問題
在其他使用 Mezzanime 的專案中有碰到, 在本專案目前的 Storybook 中沒有出現此問題 

### Steps To Reproduce
尚未確定重現步驟

### Expected behavior
clear icon 不應受無關的 prop 影響位置

**Comment by travor20814** [comment]
後來發現並非 bug，而是要注意 typography 在覆蓋時，line-height 要使用 `rem` 而非 `em`
