### ISSUE TITLE
Input readonly 時不該有 hover active 效果

### ISSUE THREAD

**Issue by syminrosie** [Mezzanine-UI/mezzanine#147]
### Describe the bug
Input readonly 時不該有 hover active（border / cursor） 效果。

### Steps To Reproduce
滑鼠滑到上面。

### Expected behavior
hover 時拔除 active 效果。

### Screenshots
![image](https://user-images.githubusercontent.com/43403595/153137609-6bcb582d-f282-4d8e-9b0f-626793980b7f.png)

**Comment by travor20814** [comment]
為了區分出 disabled / readonly
readonly 在實務上仍會讓使用者能複製文字內容，所以會有互動效果，只是不能更改內容（disabled 才會是完全無互動）
