### ISSUE TITLE
TextArea props suffixActionIcon / row 沒有作用

### ISSUE THREAD

**Issue by syminrosie** [Mezzanine-UI/mezzanine#152]
### Describe the bug
TextArea props suffixActionIcon / row 使用後沒有作用

### Steps To Reproduce
拿掉 maxLength 限制字數的 props，rows 依舊沒有作用。

### Expected behavior
1. suffixActionIcon 不確定正確效果。
2. row 要限制 TextArea 可輸入的 rows。

**Comment by travor20814** [comment]
1. suffixActionIcon 此 component 不會用到，所以 types 應拿掉
2. rows 有作用，只是因為 storybook 設定關係，高度被鎖死才會看起來沒作用
