### ISSUE TITLE
enhance declaration of TableColumn Props 

### ISSUE THREAD

**Issue by ntubrian** [Mezzanine-UI/mezzanine#203]
### Is your feature request related to a problem? Please describe.

current usage for complex rendering:
```Javascript

{
   title: "test",
   dataIndex: 'test',
   render: (source, index) => {
       ......
       return (
          .....
       )
     
   }
}
```

"dataIndex" declaration seems to be redundant because we only focus on the more complex render function.

Either declare "dataIndex" or "render" function, which means when declaring the render function the "dataIndex" key should not exist.

### Describe the solution you'd like
```Typescript
export type TableColumnBase<SourceType> = {
  tile?:  string;
   ......
}

export type TableColumn<SourceType> = 
{
  dataIndex: string;
}  & TableColumnBase<SourceType>  |    
{
  render: (...)=> any
}  & TableColumn<SourceType>
```
`

### Additional context or references
current version: 0.13.3

**Comment by travor20814** [comment]
Duplicate https://github.com/Mezzanine-UI/mezzanine/issues/136
