### ISSUE TITLE
All the form component needs to use the same logic to pass props and missing props ex.onBlur, id and name ...

### ISSUE THREAD

**Issue by stevenho0811** [Mezzanine-UI/mezzanine#55]
### Describe the bug

So why am I need to pass `id` to input, because it's will provide better accessibility when using it with `<label htmlFor="id">` recommend by W3C, and I try to pass it, use `<Input>` and I saw that provide a props call `inputProps`, and still can't pass thought it.

And another point is we want to use some third-party library (ex. formik or redux-form ...), and those packages will detect `touched`, `dirty` or something else about fields status, will use `onBlur` and `name` to approach that, many components acting different props to pass it, this is so messy and torture me ...

For examples:
-  < Input > is not accept `name` from the base props but accept in `inputProps`, but not accept `id` and `onBlur`, the heck?
- < Switch > does not accept `name` and not where can pass to `input`, the `id` also not pass it to `input`.
- < Radio > and < Checkbox > can pass `htmlFor` and binding it to `input`'s `id`, but `onBlur` can't binding on it.
- ...

For the users who use those forms, we might be like all inputs that can be used and pass props like original HTML inputs.

### Steps To Reproduce
1. Use any of the inputs
2. And settle down that input
3. Use another input
4. And been torture 😈

### Expected behavior
All the input component needs to use the same logic to pass props.

### Screenshots
![Screen Shot 2021-04-21 at 5 15 04 PM](https://user-images.githubusercontent.com/4948562/115529000-1df84900-a2c5-11eb-9578-035518917172.png)
![Screen Shot 2021-04-21 at 5 33 38 PM](https://user-images.githubusercontent.com/4948562/115531748-b5f73200-a2c7-11eb-9a38-d71d27798e40.png)

**Comment by travor20814** [comment]
As mentioned in PR https://github.com/Mezzanine-UI/mezzanine/pull/57, accessibility control properties need to be pass via `inputProps`, we have sync all the form component props to allow `inputProps` to control each native `<input>` element. Also, component types bug are fixed.

Hope this change helps.
