### ISSUE TITLE
ModalActions: color adjustment

### ISSUE THREAD

**Issue by ayogllin** [Mezzanine-UI/mezzanine#70]
### Is your feature request related to a problem? Please describe.
目前按鈕顏色受到 `Modal` 的 `severity` 限制，若有使用紅色按鈕的需求無法另行設定
實際使用
![image](https://user-images.githubusercontent.com/33858544/118606532-1f486300-b7ea-11eb-9345-fdd431007302.png)
設計需求
![image](https://user-images.githubusercontent.com/33858544/118606615-3a1ad780-b7ea-11eb-8761-d8f75208b61e.png)

### Describe the solution you'd like
`ModalActions` 可自行設定顏色樣式（透過 `severity` 或 `className`）
or
`ModalHeader` 的 Icon 可自行調整不綁定 `severity`

### Additional context or references
無

**Comment by travor20814** [comment]
By giving `cancelButtonProps` and `confirmButtonProps` to `<ModalActions />`, you are able to customize already since v0.3.0
