### ISSUE TITLE
When update(re-render) table data, not update column data.

### ISSUE THREAD

**Issue by stevenho0811** [Mezzanine-UI/mezzanine#85]
### Describe the bug
假設今天有個 GraphQL 的 query， 在進行編輯 Table 上的資料 (另開新 Modal 的那種編輯)，送出後觸發 refetchQuery，query 的 hook 有觸發資料的更新並重新 Render，確認了從 console 或其他方式查看資料是否被更新了，是有被更新的，但 Table 上顯示的資料並沒有更新。

然而如果陣列的長度有改變的話，資料是可以被添加或是移除的，唯獨每筆資料內的內容 (無論 render 或 dataIndex) 改變時不會發生改變 ...

如果有任何地方是要從我這邊這邊實作或是我個人認知錯誤都歡迎討論，目前我覺得以我使用在別的專案上比較沒有那麼急的一件事，需不需要 lock 在正式版的進度，需要 mezzanine 的開發者們討論一下🙏🏻。

### Steps To Reproduce
原資料:
```ts
const dataSource: DataType[] = Array.from(Array(10)).map((_, idx) => ({
  key: `source-${idx + 1}`,
  name: `${String.fromCharCode(97 + idx)} John Brown`,
  address: `New York No. ${idx + 1} Lake Park`,
  age: (12 + parseInt(`${((Math.random()) * 100) % 12}`, 10)) + idx,
  description: idx % 2 === 0 ? `Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure illo,
  ipsa sunt molestias culpa saepe! Minima odio repellendus officiis! Assumenda,
  consequuntur sit blanditiis culpa vel repellendus dolorum non minus doloribus.` : '',
  tel: '0912345678(no ellipsis)',
  foo: {
    bar: 'test',
  },
}));
```
新資料 (注意 name 欄位的變化):
```ts
const newDataSource: DataType[] = Array.from(Array(10)).map((_, idx) => ({
  key: `source-${idx + 1}`,
  name: `${String.fromCharCode(97 + idx)} QQ dog`,
  address: `New York No. ${idx + 1} Lake Park`,
  age: (12 + parseInt(`${((Math.random()) * 100) % 12}`, 10)) + idx,
  description: idx % 2 === 0 ? `Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure illo,
  ipsa sunt molestias culpa saepe! Minima odio repellendus officiis! Assumenda,
  consequuntur sit blanditiis culpa vel repellendus dolorum non minus doloribus.` : '',
  tel: '0912345678(no ellipsis)',
  foo: {
    bar: 'test',
  },
}));
```

建議用這段 code 下去測試
```ts
  useEffect(() => {
    const timer = setTimeout(() => {
      setSources(newDataSource);
    }, 5000);

    return () => {
      clearTimeout(timer);
    };
  }, []);
```
等待五秒後更新新的資料陣列的單筆內容做測試，情境應該一樣。

### Expected behavior
Table 欄位的單筆資料會更新

### Screenshots
![Screen Shot 2021-06-15 at 7 42 46 PM](https://user-images.githubusercontent.com/4948562/122047145-5e31fe80-ce12-11eb-9c7b-c9d46a57e52f.png)

**Comment by travor20814** [comment]
The main reason is that `dataSource` will go through the `sorting` hook by default. Since our sorting equality function is to compare `prevDataSource` & `currentDataSource` keys (we are not using deep comparison because of some performance optimization), if sources key or id not changed, the dataSource won't be marked as changed.

I think this feature may cause buggy in such situations, so we will fix this soon before v1.
