### ISSUE TITLE
React Select `fullWIdth` props does not work

### ISSUE THREAD

**Issue by Kuanisinajar** [Mezzanine-UI/mezzanine#86]
### Describe the bug
When using `Select` component the `fullWidth` does not work. This is due to the root `<div />` of `Select` component does not have `width: 100%` in its style. And currently no way to put styles or css to the `<div />` element 

### Steps To Reproduce
1. Implement `Select`
2. apply `fullWidth` like `<Select fullWidth={true} />`
3. see the component will not be full width of its parent

### Expected behavior
Be full width of its parent

### Screenshots
N/A

**Comment by travor20814** [comment]
Note: This happened only when parent element is flex box. I will fix this soon.
