### ISSUE TITLE
Select Multiple not display when value updated

### ISSUE THREAD

**Issue by fantasywind** [Mezzanine-UI/mezzanine#98]
### Describe the bug
Select in multiple mode can not display selected options on value updated

### Steps To Reproduce
1. set value is []
2. update value to [...options]

### Expected behavior
Select input should display the selected options tag

### Screenshots
![Screen Shot 2021-08-26 at 20 11 47](https://user-images.githubusercontent.com/1902526/130961128-fad943e0-45a2-4d2c-8761-89935d36040f.png)
![Screen Shot 2021-08-26 at 20 11 57](https://user-images.githubusercontent.com/1902526/130961139-54b542b2-06f8-42dd-a726-9e3fc2b25852.png)

**Comment by travor20814** [comment]
fixed at `v0.6.4`
